### ISSUE TITLE
Add master branch and version 2.0.0

### ISSUE THREAD

**Issue by alberto-sanchez** [cms-externals/evtgen#1]
Can the package be update, e.g. add branch cms/2.0.0
and also if possible master.

The master repo is at https://phab.hepforge.org/source/evtgen.git

I already have made the exercise in my fork, but I am not able to make a pull request, to include this new branch (tag).

We are planning to upgrade to 2.0.0 as early as possible. 
I have everything in place, but this

**Comment by alberto-sanchez** [comment]
Dear Patrick (@gartung). Do you mind in updating this package?. -- best regards Alberto

**Comment by gartung** [comment]
@alberto-sanchez Done. I pushed the master branch and tags from your repo https://github.com/alberto-sanchez/evtgen. It looks like you need to push the R02-00-00 tag.

**Comment by alberto-sanchez** [comment]
@gartung, the correct should be

https://phab.hepforge.org/source/evtgen

or 

https://github.com/alberto-sanchez/evtgen-cms

which is the fork

https://github.com/cms-externals/evtgen

**Comment by gartung** [comment]
OK. I updated the master branch from your fork. I also push the 2.0.0 branch.

**Comment by alberto-sanchez** [comment]
thanks a lot @gartung.
